name: Jay Graves
favicon: null
layout_spectrum: 0.20996870193630457
typography_spectrum: 0.7653501806780696
title: Jay Graves
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56292295-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.026518681785091758
  lightness: 0.5304408299271017
  saturation: 0.482161870226264
  rhythmicContrast: 0.4239941658452153
purpose: []
